version: '2'
services:
  hc:
    restart: unless-stopped
    image: conceptant/healthy-citizen-widgets:latest
    ports:
      - 8080:8000
    volumes:
      - /data/logs:/var/logs/hc
      - /data/www:/adp-backend-v5/model/public
    env_file:
      - .env
    links:
      - db
      - redis

  db:
    restart: unless-stopped
    image: mongo:4.2
    command: --noIndexBuildRetry --setParameter diagnosticDataCollectionEnabled=false --setParameter maxIndexBuildMemoryUsageMegabytes=20000 --setParameter failIndexKeyTooLong=false --setParameter cursorTimeoutMillis=6000000 --setParameter internalQueryExecMaxBlockingSortBytes=2147483647
    ports:
      - "27017"
    volumes:
      - /data/db:/data/db

  redis:
    restart: unless-stopped
    image: redis:5.0
    ports:
      - "6379"

  nginx:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - 8080
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
